FROM node
RUN apt-get update
RUN git clone https://github.com/simplicitesoftware/nodejs-demo.git
WORKDIR /nodejs-demo/
RUN npm install -g nodemon
RUN npm install -g npm@7.5.1
RUN npm install
RUN sed -i "s/localhost/0.0.0.0/g" app.js
CMD npm start
